syntax = "proto3";

package bimip_server;

service BimipService {
  rpc BimipTunnel (stream TunnelMessage) returns (stream TunnelMessage) {}
}

message TunnelMessage {
  string id = 1;
  int32 node_id = 2;
  int32 target_node_id = 3;
  State state = 4;
  Direction direction = 5;
  bytes payload = 6;
  ActionType action_type = 7;
  int64 timestamp = 8;
}

enum Direction {
    DIR_UNKNOWN = 0;
    CLIENT_TO_SERVER = 1;
    SERVER_TO_CLIENT = 2;
  }

enum State {
    UNKNOWN = 0;
    CONNECT = 1;
    DISCONNECT = 2;
    COMMUNICATION = 3;
    HEARTBEAT = 4;
  }

  enum ActionType {
    ACTION_UNKNOWN = 0;
    FORWARD = 1;          // Route this message to another node
    RECEIPT = 2;          // Acknowledge a received message
    PRESENCE_UPDATE = 3;  // Update status (Online/Away/Busy)
  }

